import numpy as np
from numpy import *
# A = np.array([[1,2,3],[2,4,6]])
# print("The dimision of A is %d"%A.ndim)
# print("The shape of A is", A.shape)
# print("The size of A is %d"%A.size)
# b=np.arange(15).reshape(3,5)
# print(b)
# B = np.array([1,2,3])
# print(B)
# print(B.shape)
# print(B.ndim)
# B=B[np.newaxis,:]
# print(B)
# C = np.zeros((3,3))
# print(C)
# D = np.arange(10)
# print(D)
# E= D.reshape(2,5)
# print(E)
# print(np.dot(A,b))
# print(A*B)
# print(np.transpose(A))
# print(A[1,1])
a1 = np.array([[1,2,3]])
a2 = np.array([[3,4,5]])
print(np.hstack((a1,a2)))
print(np.vstack((a1,a2)))
print(np.sin(1))
print(np.cos(1))
print(np.exp(1))
print(a1[0,:])
print(a1[0,1:2])
print(a1[0,-1])